const COMPLETE_TASK_REQUEST = 'COMPLETE_TASK_REQUEST';
const COMPLETE_TASK_FAILURE = 'COMPLETE_TASK_FAILURE';
const COMPLETE_TASK_SUCCESS = 'COMPLETE_TASK_SUCCESS';
const GET_TASK_APP_DATA_REQUEST = 'GET_TASK_APP_DATA_REQUEST';
// const GET_TASK_APP_DATA_SUCCESS = 'GET_TASK_APP_DATA_SUCCESS';
const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
const CLOSE_TASK = "CLOSE_TASK";

export {
    COMPLETE_TASK_REQUEST,
    COMPLETE_TASK_FAILURE,
    COMPLETE_TASK_SUCCESS,
    CLEAR_ERROR_MESSAGE,
    CLOSE_TASK,
    GET_TASK_APP_DATA_REQUEST,
    // GET_TASK_APP_DATA_SUCCESS
};
