const COMPLETE_TASK_REQUEST = 'COMPLETE_TASK_REQUEST';
const COMPLETE_TASK_FAILURE = 'COMPLETE_TASK_FAILURE';
const COMPLETE_TASK_SUCCESS = 'COMPLETE_TASK_SUCCESS';
const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
const CLOSE_TASK = "CLOSE_TASK";

export { COMPLETE_TASK_REQUEST, COMPLETE_TASK_FAILURE, COMPLETE_TASK_SUCCESS, CLEAR_ERROR_MESSAGE, CLOSE_TASK };
