const CREATE_PROCESS_REQUEST = 'CREATE_PROCESS_REQUEST';
const CREATE_PROCESS_FAILURE = 'CREATE_PROCESS_FAILURE';
const CREATE_PROCESS_SUCCESS = 'CREATE_PROCESS_SUCCESS';
const CLEAR_CREATE_ERROR_MESSAGE = "CLEAR_CREATE_ERROR_MESSAGE";
const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";

export { CREATE_PROCESS_REQUEST, CREATE_PROCESS_FAILURE, CREATE_PROCESS_SUCCESS, CLEAR_CREATE_ERROR_MESSAGE, CLOSE_CREATE_MODAL };
