const GET_TASKLIST_REQUEST = 'GET_TASKLIST_REQUEST';
const GET_TASKLIST_FAILURE = 'GET_TASKLIST_FAILURE';
const GET_TASKSDATA_SUCCESS = 'GET_TASKSDATA_SUCCESS';

export { GET_TASKLIST_REQUEST, GET_TASKLIST_FAILURE, GET_TASKSDATA_SUCCESS };
